import { LineEdit, VerticalBox, Button } from "std-widgets.slint";

component MemoryTile inherits Rectangle {
    GridLayout {
        Row {
            Text {
                text: "Enter Total Income";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
            }
        }

        Row {
            LineEdit {
                font-size: 16px;
                width: 200px;
                height: 25px;
                placeholder-text: "Enter your number0";
            }

            VerticalBox {
                Button {
                    text: "Calculate";
                    clicked => {
                        self.text = "Clicked";
                    }
                }
            }
        }

        Row { }
    }

    callback clicked;
    in property <bool> open_curtain;
    in property <bool> solved;
    in property <image> icon;
    height: 64px;
    width: 64px;
    background: solved ? #34CE57 : #3960D5;
    animate background { duration: 800ms; }
    Image {
        source: icon;
        width: parent.width;
        height: parent.height;
    }

    // Left curtain
    Rectangle {
        background: #193076;
        x: 0px;
        width: open_curtain ? 0px : (parent.width / 2);
        height: parent.height;
        animate width {
            duration: 250ms;
            easing: ease-in;
        }
    }

    // Right curtain
    Rectangle {
        background: #193076;
        x: open_curtain ? parent.width : (parent.width / 2);
        width: open_curtain ? 0px : (parent.width / 2);
        height: parent.height;
        animate width {
            duration: 250ms;
            easing: ease-in;
        }
        animate x {
            duration: 250ms;
            easing: ease-in;
        }
    }

    TouchArea {
        clicked => {
            // Delegate to the user of this element
            root.clicked();
        }
    }
}

export component MainWindow inherits Window {
    width: 326px;
    height: 326px;
    MemoryTile {
        icon: @image-url("icons/bus.jpg");
        clicked => {
            self.open_curtain = !self.open_curtain;
        }
    }
}
