import { LineEdit, VerticalBox, Button } from "std-widgets.slint";

export component AppWindow inherits Window {
    in property <string> results:"";
    callback cheapest-fly(string, string, string);
    background: #313e50;
    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row {
            Text {
                text: "Cheapest Fly Ticket";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
            }
        }

        Row {
            departureFrom := LineEdit {
                horizontal-alignment: center;
                font-size: 16px;
                width: 240px;
                height: 35px;
                placeholder-text: "From";
            }

            departureTo := LineEdit {
                horizontal-alignment: center;
                font-size: 16px;
                width: 240px;
                height: 35px;
                placeholder-text: "To";
            }

            flyDateTime := LineEdit {
                horizontal-alignment: center;
                font-size: 16px;
                width: 240px;
                height: 35px;
                placeholder-text: "Ticket date time";
            }
        }

        Row {
            Button {
                text: "Calculate";
                primary: true;
                height: 35px;
                width: 240px;
                clicked => {
                    cheapest-fly(departureFrom.text,departureTo.text,flyDateTime.text)
                }
            }

            Button {
                text: "Refresh";
                primary: true;
                height: 35px;
                width: 240px;
                clicked => {
                }
            }
        }

        Row {
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background: #f2f2f2;
                    Text {
                        color: black;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.results;
                    }
                }
            }
        }
    }
}
